- name: Install Apt Packages
  become: true
  apt:
    pkg:
    - qemu
    - virt-manager
    - qemu-kvm
    - qemu-utils
    - ovmf
    - libvirt-daemon-system
    - libvirt-clients
    - bridge-utils
    - swtpm-tools

- name: copy libvirt hooks into place
  become: true
  copy:
    src: ./kvm/hooks
    dest: /etc/libvirt
    owner: root
    group: root
    mode: '0755'
    
- name: Check kernel options
  become: true
  command: kernelstub -p
  register: kernel_options
  changed_when: kernel_options.stderr is not search(item)
  with_items:
  - "amd_iommu=on"
  - "kvm.ignore_msrs=1"

- name: Add kernel options to kernelstub
  become: true
  command: kernelstub -a "amd_iommu=on kvm.ignore_msrs=1"
  when: kernel_options is changed
  notify: reboot

# based mostly on https://github.com/bryansteiner/gpu-passthrough-tutorial

# Add TMP module to boot windows 11
# https://www.smoothnet.org/qemu-tpm/

# Add Resiazable Bar 64GB to fit video ram address space
# https://www.reddit.com/r/VFIO/comments/qx4rg7/can_anyone_else_confirm_that_vfio_doesnt_work_w/
# 


# 01:00.0 - nvidia
# 01:00.1 - nvidia

# 10de:2684
# 10de:22ba

# bus 003 - 0000:14:00.0 - attach KVM 1 - Red above Ethernet
# bus 005 - 0000:17:0003 - attach KVM 4 - Red above usb-c

