---
- name: Set /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 mars'

- name: Set /etc/hostname
  become: yes
  lineinfile:
    path: /etc/hostname
    regexp: '.*'
    line: mars

# - name: Set hostname
#   become: yes
#   hostname:
#     name: mars