---
- name: Set /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 regium'

- name: Set /etc/hostname
  become: true
  lineinfile:
    path: /etc/hostname
    regexp: '.*'
    line: regium

- name: Set hostname
  become: true
  hostname:
    name: regium
