---
- hosts: localhost
  roles:
    # - role: xps_9560
    #   tags: hardware
    #   when: ansible_product_name == "XPS 15 9560"

    # - role: razer_blade_stealth
    #   tags: hardware
    #   when: ansible_product_name == "Blade Stealth"

    - role: hostname
      tags: hostname

    - role: common
      tags: common

    - role: user
      tags: user

    - role: zsh_theme
      tags: zsh_theme

    - role: npm
      tags: npm

    - role: keyboard_shortcuts
      tags: keyboard_shortcuts

    - role: wallpaper
      tags: wallpaper