---
- name: Create ~/bin
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: 0755

- name: User - shell to zsh, groups to docker,vboxuser
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    # generate_ssh_key: yes
    groups:
      - docker
      - plugdev
      # - vboxusers
    shell: /usr/bin/zsh
    append: yes

- name: Set git co alias
  git_config:
    name: alias.co
    value: checkout
    scope: global

- name: Set git user
  git_config:
    name: user.name
    value: Jason Greathouse
    scope: global

- name: Set git email
  git_config:
    name: user.email
    value: jgreat@jgreat.me
    scope: global

- name: Link rancher-get-kubeconfig.sh script
  copy:
    dest: "{{ ansible_env.HOME }}/bin/rancher-get-kubeconfig.sh"
    src: ./scripts/rancher-get-kubeconfig.sh
    mode: 0755
