---
- name: Create ~/bin
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: 0755

- name: User - shell to zsh, groups to docker,vboxuser
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    # generate_ssh_key: yes
    groups:
      - docker
      - vboxusers
      - plugdev
    shell: /usr/bin/zsh
    append: yes

- name: Set git co alias
  git_config:
    name: alias.co
    value: checkout
    scope: global

- name: Set git github include
  git_config:
    name: includeIf.gitdir:git/github.com/**.path
    value: .gitconfig-github.com
    scope: global

- name: github.com include
  copy:
    dest: "{{ ansible_env.HOME }}/.gitconfig-github.com"
    content: |
      [user]
      	name = Jason Greathouse
      	email = jgreat@jgreat.me

- name: Link vte for tilix
  become: yes
  file:
    state: link
    src: /etc/profile.d/vte-2.91.sh
    dest: /etc/profile.d/vte.sh

- name: Set vte in .zshrc for tilix
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
      fi

- name: Do bad things with known_hosts
  blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    create: yes
    block: |
      host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
