---
- name: Add kernel parameters to grub
  become: yes
  lineinfile:
    path: "/etc/default/grub"
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="button.lid_init_state=open i915.enable_rc6=0 quiet splash"'
  register: grub

- name: Run update-grub
  become: yes
  command: update-grub
  when: grub|changed
  notify: reboot
