---
- name: Install Apt Keys
  become: yes
  apt_key:
    id: "{{ item.id }}"
    url: "{{ item.url }}"
  register: keys
  with_items:
    # NodeJS
    - id: 68576280
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    # Enpass
    - id: 9798C2FC
      url: https://dl.sinew.in/keys/enpass-linux.key
    # Google
    - id: D38B4796
      url: https://dl.google.com/linux/linux_signing_key.pub
    # Microsoft
    - id: BE1229CF
      url: https://packages.microsoft.com/keys/microsoft.asc
    # Docker
    - id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
    # Virtualbox
    - id: 2980AECF
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    # Tilix
    - id: EEA14886
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7B2C3B0889BF5709A105D03AC2518248EEA14886

- name: Install Apt Repos
  become: yes
  apt_repository:
    filename: "{{ item.file }}"
    repo: "{{ item.repo }}"
  register: repos
  with_items:
    - file: nodesource
      repo: deb https://deb.nodesource.com/node_10.x {{ ansible_lsb.codename }} main
    - file: enpass
      repo: deb http://repo.sinew.in/ stable main
    - file: google-chrome
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    - file: azurecli
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main
    - file: docker
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable
    - file: virtualbox
      repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib
    - file: tilix
      repo: deb http://ppa.launchpad.net/webupd8team/terminix/ubuntu artful main

- name: Update Apt Cache
  become: yes
  apt:
    update_cache: yes
  when: repos is changed or keys is changed

- name: Install Apt Packages
  become: yes
  apt:
    pkg:
    - azure-cli
    - code
    - docker-ce
    - gimp
    - google-chrome-stable
    - jq
    - nautilus-image-converter
    - network-manager-openvpn-gnome
    - nodejs
    - openvpn-systemd-resolved
    - python-psutil
    - python3-pip
    - snapd
    - steam
    - tilix
    - vim
    - virtualbox-5.2
    - zsh

- name: Install awscli
  become: yes
  pip:
    name: awscli
    executable: pip3

- name: Check installed snaps
  become: yes
  command: snap list
  register: snaps
  changed_when: snaps.stdout is not search(item)
  with_items:
    - slack
    - kubectl

- name: Install snaps
  become: yes
  command: snap install {{ item }} --classic
  when: snaps is changed
  with_items:
    - slack
    - kubectl

- name: Install zoom
  become: yes
  apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb
