---
- name: Install Apt Keys
  become: yes
  apt_key:
    id: "{{ item.id }}"
    url: "{{ item.url }}"
  register: keys
  with_items:
    # NodeJS
    - id: 68576280
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    # Enpass
    - id: 9798C2FC
      url: https://dl.sinew.in/keys/enpass-linux.key
    # Google
    - id: D38B4796
      url: https://dl.google.com/linux/linux_signing_key.pub
    # Microsoft
    - id: BE1229CF
      url: https://packages.microsoft.com/keys/microsoft.asc
    # Docker
    - id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
    # Signal
    - id: 57F6FB06
      url: https://updates.signal.org/desktop/apt/keys.asc
    # Virtualbox
    # - id: 2980AECF
    #   url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    # # Tilix
    # - id: EEA14886
    #   url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7B2C3B0889BF5709A105D03AC2518248EEA14886
    # # Ukuu
    # - id: 2D0F61F0
    #   url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1B32B87ABAEE357218F6B48CB5B116B72D0F61F0

- name: Install Apt Repos
  become: yes
  apt_repository:
    filename: "{{ item.file }}"
    repo: "{{ item.repo }}"
  register: repos
  with_items:
    - file: nodesource
      repo: deb https://deb.nodesource.com/node_16.x {{ ansible_lsb.codename }} main
    - file: enpass
      repo: deb http://repo.sinew.in/ stable main
    - file: google-chrome
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    - file: docker
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    - file: microsoft-vscode
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
    - file: microsoft-azure-cli
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli {{ ansible_lsb.codename }} main
    - file: signal
      repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    # - file: virtualbox
    #   repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib


# - name: Accept virtualbox ext pack license
#   become: yes
#   debconf:
#     name: virtualbox-ext-pack
#     question: virtualbox-ext-pack/license
#     value: 'true'
#     vtype: select

- name: Install Apt Packages
  become: yes
  apt:
    pkg:
    - docker-ce
    - enpass
    - gimp
    - gnome-shell-extension-appindicator
    - google-chrome-stable
    - jq
    - nautilus-image-converter
    - nodejs
    - snapd
    - steam
    - tilix
    - vim
    - zsh
    - code
    - signal-desktop
    - python3-pip


- name: Install awscli
  become: yes
  pip:
    name: awscli
    executable: pip3

- name: Install docker-compose
  become: yes
  pip:
    name: docker-compose
    executable: pip3

- name: Check installed snaps
  become: yes
  command: snap list
  register: snaps
  changed_when: snaps.stdout is not search(item)
  with_items:
    - slack
    - kubectl
    - multipass
    - helm
    - kontena-lens

- name: Install snaps
  become: yes
  command: snap install {{ item }} --classic
  when: snaps is changed
  with_items:
    - slack
    - kubectl
    - multipass
    - helm
    - kontena-lens

#- name: Install zoom
#  become: yes
#  apt:
#    deb: https://zoom.us/client/latest/zoom_amd64.deb
  
