---
- name: Install Apt Keys
  become: true
  apt_key:
    id: "{{ item.id }}"
    url: "{{ item.url }}"
    keyring: "{{ item.keyring }}"
  register: keys
  with_items:
    # NodeJS
    - id: 68576280
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      keyring: /etc/apt/trusted.gpg.d/nodejs.gpg
    # Enpass
    - id: 9798C2FC
      url: https://dl.sinew.in/keys/enpass-linux.key
      keyring: /etc/apt/trusted.gpg.d/enpass.gpg
    # Microsoft
    - id: BE1229CF
      url: https://packages.microsoft.com/keys/microsoft.asc
      keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    # Docker
    - id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /etc/apt/trusted.gpg.d/docker.gpg
    # Google
    # - id: D38B4796
    #   url: https://dl.google.com/linux/linux_signing_key.pub
    #   keyring: /etc/apt/trusted.gpg.d/google.gpg
    # Virtualbox
    # - id: 2980AECF
    #   url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Install Apt Repos
  become: true
  apt_repository:
    filename: "{{ item.file }}"
    repo: "{{ item.repo }}"
  register: repos
  with_items:
    - file: nodesource
      repo: deb https://deb.nodesource.com/node_16.x {{ ansible_lsb.codename }} main
    - file: enpass
      repo: deb https://apt.enpass.io/ stable main
    - file: docker
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    - file: vscode
      repo: deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main
    - file: microsoft-azure-cli
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli {{ ansible_lsb.codename }} main
    # - file: google-chrome
    #   repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    # - file: virtualbox
    #   repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib


# - name: Accept virtualbox ext pack license
#   become: true
#   debconf:
#     name: virtualbox-ext-pack
#     question: virtualbox-ext-pack/license
#     value: 'true'
#     vtype: select

- name: Install Apt Packages
  become: true
  apt:
    pkg:
    - docker-ce
    - docker-compose-plugin
    - enpass
    - gimp
    - gnome-shell-extension-appindicator
    - jq
    - nautilus-image-converter
    - nodejs
    - tilix
    - vim
    - zsh
    - code
    - python3-pip
    - azure-cli
    - awscli
    - snapd
    - libsensors-dev
    - libsensors5
    - lm-sensors
    - psensor

- name: Install Snaps
  become: true
  community.general.snap:
    name:
      - kubectl
      - multipass
      - helm
    classic: true

- name: Install flatpacks
  community.general.flatpak:
    name: "{{ item }}"
    method: user
  with_items:
    - us.zoom.Zoom
    - org.signal.Signal
    - com.slack.Slack
    - com.google.Chrome
